# Generated by Django 4.2.5 on 2023-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
