# Generated by Django 4.2.6 on 2023-10-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='quantity',
            new_name='quantity_of_students',
        ),
        migrations.RemoveField(
            model_name='group',
            name='average_score',
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
