# Generated by Django 4.2.6 on 2023-10-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='getting_started',
            new_name='start_date',
        ),
    ]
